[
  [ "bird-lg" ]
  [ "dma" ]
  [ "drep" ]
  [ "dyndnsc" ]
  [ "esbuild" ]
  [ "guile-commonmark" ]
  [ "guile-json" ]
  [ "haunt" ]
  [ "iwgtk" ]
  [ "linuxPackages" "rtl8723bu" ]
  [ "linuxPackages_latest" "rtl8723bu" ]
  [ "python3Packages" "daemonocle" ]
  [ "shellharden" ]
  [ "trust-dns" ]
]
